Bumps Go version to 1.19 due to url.JoinPath
Running under `1.18` causes the following error:

```
internal/cmdapi/vercheck/vercheck.go:72:23: undefined: url.JoinPath
```